name: Test build

on:
  [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04, macos-11, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install packaged dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then sudo apt-get update; fi
        if [[ "$RUNNER_OS" == "Linux" ]]; then sudo apt-get install libmp3lame-dev libshout3-dev libconfig++-dev libfftw3-dev librtlsdr-dev libsoapysdr-dev libpulse-dev; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then brew update; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then brew install lame libshout libconfig fftw librtlsdr soapysdr pulseaudio; fi

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: VERBOSE=1 cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build

    - name: Test run
      run: /usr/local/bin/rtl_airband -v
